Set rbenv to 2.1.7; try reloading database before report generation
I am having an issue on our build server where it's unable to generate
the AuthorsReport, but there doesn't seem to be any obvious cause:

`gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:471:in `block in merge_target_lists': undefined method `keys' for 0:Fixnum (NoMethodError)`